name: Create GitHub Repo

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true
        type: string
      private:
        required: true
        type: string
        default: "true"
      port_run_id:
        description: "Port action run id"
        required: true
        type: string


jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository
        shell: bash
        run: |
          set -euo pipefail
          
          echo "Creating repo: '${{ inputs.repo_name }}' (private=${{ inputs.private }})"
          
          http_code=$(
            curl -sS -o response.json -w "%{http_code}" \
          -X POST https://api.github.com/user/repos \
          -H "Authorization: Bearer ${{ secrets.PORT_SECRET_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{
            "name": "${{ inputs.repo_name }}",
            "private": ${{inputs.private == 'true' }}
           }'
          )
          
          echo "HTTP status: $http_code"
          echo "Response:"
          cat response.json
          echo ""
          if [[ "$http_code" =~ ^2 ]]; then
            echo "SUCCESS: Repo '${{ inputs.repo_name }}' created."
          else
            echo "FAILURE: Repo creation failed."
            exit 1
          fi

      - name: Notify port (always)
        if: always()
        shell: bash
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            status="success"
            LABEL="Repo created successfully"
          else
            status="failure"
            LABEL="Repo creation failed"
          fi
          
          curl -sS -X PATCH "https://api.getport.io/v1/actions/runs/${{ inputs.port_run_id }}" \
            -H "Authorization: Bearer ${{ secrets.PORT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"status\": \"${STATUS}\",
              \"statusLabel\": \"${LABEL}\"
            }"
